version: "3.9"

services:
  frontend:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: ${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/3-service/backend:latest
    working_dir: /app
    volumes:
      - ./backend:/app
    command: python app.py
    environment:
      - DATABASE_HOST=mysql_container
      - DATABASE_USER=root
      - DATABASE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DATABASE_NAME=appdb
    depends_on:
      - mysql_container
    networks:
      - app-network
      - back-network

  mysql_container:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=appdb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - back-network

volumes:
  mysql_data:
networks:
  app-network:
    driver: bridge
  back-network:
    driver: bridge
