name: Build , Test, Push to ECR, and Deplot to EC2
on:                                           
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Set up environment variables
        run: echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> $GITHUB_ENV
        
      - name: Build and start the services
        run: docker-compose up -d --build
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

      - name: Test app
        run: |
          sleep 10
          curl -f http://localhost:8080 || exit 1

      - name: Test backend (Flask) internally
        run: |
          BACKEND_CONTAINER=$(docker-compose ps -q backend)  # Get the container ID of the backend service
          docker exec $BACKEND_CONTAINER curl -f http://localhost:5000/api/data || exit 1

      - name: Test MySQL container
        run: |
          MYSQL_CONTAINER=$(docker-compose ps -q mysql_container)  # Get the container ID of the MySQL service
          docker exec $MYSQL_CONTAINER mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "SHOW DATABASES;" || exit 1
          


      - name: Destroy the environment
        run: docker-compose down -v

  push_to_ecr:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 --profile iamadmin-general | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
      
      - name: Build the backend Docker image
        run: |
          docker build -t backend ./backend
          docker tag backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/3-service/backend:latest

      - name: Push the backend image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/3-service/backend:latest

      
#  deploy:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2

#      - name: Set up AWS CLI
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-west-2

#      - name: Fetch DB password from AWS Secrets Manager
#        run: |
#          export DB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id db_password --query SecretString --output text)
#          echo "$DB_PASSWORD" | docker secret create db_password -
        
#      - name: Deploy containers with Docker Compose
#        run: docker-compose -f docker-compose.prod.yml up -d

# ========= OR ==========
#  deploy:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2

#      - name: Set up Docker
#        uses: docker/setup-buildx-action@v2

#      - name: Set up Docker Secrets from GitHub Secrets
#        run: |
#          echo "$DB_PASSWORD" | docker secret create db_password -
#        env:
#          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}  # Inject the GitHub secret as an env var

#      - name: Deploy containers with Docker Compose
#        run: docker-compose -f docker-compose.prod.yml up -d


      


